apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: stream-montages
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: jtengco-stream-montages-api-gw:0.0.1
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        env:
        - name: KRAKEND_PORT
          value: "8080"
        resources:
          limits:
            cpu: "1"
            memory: "128Mi"
          requests:
            cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: stream-montages
  labels:
    app: api-gateway
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30490
  selector:
    app: api-gateway
