apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-repo
  namespace: stream-montages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-repo
  template:
    metadata:
      labels:
        app: jobs-repo
    spec:
      containers:
      - name: jobs-repo
        image: jtengco-stream-montages-jobs-repo:0.0.1
        envFrom:
        - secretRef:
            name: postgres-cnx-secrets
        env:
        - name: SM_KAFKA_BOOTSTRAP_SERVER
          value: kafka-service.kafka.svc.cluster.local:9092
        - name: SM_KAFKA_CLIENT_ID
          value: stream-montages-app-job-repo
        - name: SM_KAFKA_JOBS_TOPIC
          value: stream-montage-jobs
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"

---

kind: Service
apiVersion: v1
metadata:
  name: jobs-repo-service
  namespace: stream-montages
spec:
  selector:
    app: jobs-repo
  type:  ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
