apiVersion: apps/v1
kind: Deployment
metadata:
  name: montages-repo
  namespace: stream-montages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: montages-repo
  template:
    metadata:
      labels:
        app: montages-repo
    spec:
      containers:
      - name: montages-repo
        image: jtengco-stream-montages-montages-repo:0.0.1
        envFrom:
        - secretRef:
            name: postgres-cnx-secrets
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"

---

kind: Service
apiVersion: v1
metadata:
  name: montages-repo-service
  namespace: stream-montages
spec:
  selector:
    app: montages-repo
  type:  ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
