apiVersion: v1
kind: Service
metadata:
  name: montages-repo-debug-service
  namespace: stream-montages
  labels:
    app: montages-repo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30477
  selector:
    app: montages-repo