apiVersion: apps/v1
kind: Deployment
metadata:
  name: nen-montage-jobs-scheduler
  namespace: stream-montages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nen-scheduler
  template:
    metadata:
      labels:
        app: nen-scheduler
    spec:
      containers:
      - name: nen-montage-jobs-scheduler
        image: jtengco/stream-montages-nen-scheduler:0.0.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: nen-scheduler-aws-secrets
        env:
        - name: SM_JOBS_REPO_URL
          value: http://jobs-repo-service:8080/montages/jobs
        resources:
          limits:
            cpu: "1"
            memory: "128Mi"
          requests:
            cpu: "0.5"

---

kind: Service
apiVersion: v1
metadata:
  name: nen-scheduler-service
  namespace: stream-montages
spec:
  selector:
    app: nen-scheduler
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
