apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: stream-montages
type: Opaque
stringData:
  password: postgres # meant for local dev, NOT suitable if moving to cloud

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: stream-montages
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/k8s/postgres/data" # docker desktop on Windows, adjust path accordingly

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: stream-montages
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: stream-montages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      containers:
      - name: postgres
        image: postgres:15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pv

---

kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  namespace: stream-montages
spec:
  selector:
    app: postgres
  type:  ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
