apiVersion: v1
kind: Service
metadata:
  name: postgres-debug-service
  namespace: stream-montages
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30475
  selector:
    app: postgres