apiVersion: v1
kind: Service
metadata:
  name: jobs-repo-debug-service
  namespace: stream-montages
  labels:
    app: jobs-repo
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30476
  selector:
    app: jobs-repo
